kind = "DojoContract"
class_hash = "0x56093b60a0b0aa8902f1dd09a888754a910967e4029bb70d8983ee846d4f488"
original_class_hash = "0x56093b60a0b0aa8902f1dd09a888754a910967e4029bb70d8983ee846d4f488"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/bytebeasts-battle_system-461868ac.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-battle_system"
manifest_name = "bytebeasts-battle_system-461868ac"
