kind = "DojoContract"
class_hash = "0x26ce110d44d925e05ce62603ad698824266db3199eb9a549e996cd94b94dd73"
original_class_hash = "0x26ce110d44d925e05ce62603ad698824266db3199eb9a549e996cd94b94dd73"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/bytebeasts-battle_system-461868ac.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-battle_system"
manifest_name = "bytebeasts-battle_system-461868ac"
