kind = "DojoContract"
class_hash = "0x5efdb80629807631b0bb916ce067881084b4aca4aaf22da3794172290bbd232"
original_class_hash = "0x5efdb80629807631b0bb916ce067881084b4aca4aaf22da3794172290bbd232"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/bytebeasts-battle_system-461868ac.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-battle_system"
manifest_name = "bytebeasts-battle_system-461868ac"
