kind = "DojoContract"
class_hash = "0x4b08686fca2f358e9aefa463d148f116af077fd9ce8cdf4d003ad4231b5493c"
original_class_hash = "0x4b08686fca2f358e9aefa463d148f116af077fd9ce8cdf4d003ad4231b5493c"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/bytebeasts-battle_system-461868ac.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-battle_system"
manifest_name = "bytebeasts-battle_system-461868ac"
