kind = "DojoContract"
class_hash = "0x3263aa182dfcc4dad891c9ccc739daa8b6ee3e60d9847982dcf8c6e02d34277"
original_class_hash = "0x3263aa182dfcc4dad891c9ccc739daa8b6ee3e60d9847982dcf8c6e02d34277"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/bytebeasts-actions-648ac931.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-actions"
manifest_name = "bytebeasts-actions-648ac931"
