kind = "DojoContract"
class_hash = "0x1c7fc6d32156a6ca1eb2cf46236cf84a820b475c3f9bbb22fdbfc70ba5d7270"
original_class_hash = "0x1c7fc6d32156a6ca1eb2cf46236cf84a820b475c3f9bbb22fdbfc70ba5d7270"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/bytebeasts-actions-648ac931.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-actions"
manifest_name = "bytebeasts-actions-648ac931"
