kind = "DojoContract"
class_hash = "0x2ad32bf6985d0844c17f0349e54787ac58a5804897fa82af0c5ee8c6946880d"
original_class_hash = "0x2ad32bf6985d0844c17f0349e54787ac58a5804897fa82af0c5ee8c6946880d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/bytebeasts-battle_system-461868ac.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-battle_system"
manifest_name = "bytebeasts-battle_system-461868ac"
