kind = "DojoContract"
class_hash = "0x7e81996099f49a419fe3e28fbd4a2fc04861baa0fe7f0680d10c3672ecee7e2"
original_class_hash = "0x7e81996099f49a419fe3e28fbd4a2fc04861baa0fe7f0680d10c3672ecee7e2"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/bytebeasts-battle_system-461868ac.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-battle_system"
manifest_name = "bytebeasts-battle_system-461868ac"
