kind = "DojoContract"
class_hash = "0x606970c56eebee58c296614b84bd5d990dbf1fe7bd4a68da3c2fb050cde70f6"
original_class_hash = "0x606970c56eebee58c296614b84bd5d990dbf1fe7bd4a68da3c2fb050cde70f6"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/bytebeasts-battle_system-461868ac.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-battle_system"
manifest_name = "bytebeasts-battle_system-461868ac"
