kind = "DojoContract"
class_hash = "0x153d3b6c19c130e1f6028634213cdc5f9f9236db13f9d03afe371c4163bbbd6"
original_class_hash = "0x153d3b6c19c130e1f6028634213cdc5f9f9236db13f9d03afe371c4163bbbd6"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/bytebeasts-battle_system-461868ac.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-battle_system"
manifest_name = "bytebeasts-battle_system-461868ac"
