[world]
kind = "WorldContract"
class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
original_class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x644001b28f89e7ae8a39f9c48eb4961cc4f817dc40b4b527f851a56fe703652"
transaction_hash = "0x1f1c658f1b3de98e21e98839833fb636773cf806eb7d2e3d3ec52e35c35a78"
block_number = 3
seed = "bytebeasts"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://0.0.0.0:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x4854bb6cc04b51e5adaed76afc0664091182fe44a9e5e68dc4f8f5f59ffd464"
class_hash = "0x194fab2764a0d823cb5aa7ef9810113952c3579700e114d409c33f954f0caf9"
original_class_hash = "0x194fab2764a0d823cb5aa7ef9810113952c3579700e114d409c33f954f0caf9"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/bytebeasts-actions-648ac931.json"
reads = []
writes = [
    "bytebeasts-Beast",
    "bytebeasts-Mt",
    "bytebeasts-Player",
    "bytebeasts-Potion",
]
init_calldata = []
tag = "bytebeasts-actions"
manifest_name = "bytebeasts-actions-648ac931"

[[contracts]]
kind = "DojoContract"
address = "0x612b684f6b34356ad9a07ac3e1924f9dfa54235d0a513095b0d12695ace8b68"
class_hash = "0x42e8d9b08e8c71fee2c025922e8bcd10b9277fb688e97701f2169ca03ad91c0"
original_class_hash = "0x42e8d9b08e8c71fee2c025922e8bcd10b9277fb688e97701f2169ca03ad91c0"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/bytebeasts-battle_system-461868ac.json"
reads = []
writes = []
init_calldata = []
tag = "bytebeasts-battle_system"
manifest_name = "bytebeasts-battle_system-461868ac"

[[models]]
kind = "DojoModel"
class_hash = "0x1279ba311b8f42dceefdfc2f10b1e8d524a9df7f08a0716eccc3bedf6e235da"
original_class_hash = "0x1279ba311b8f42dceefdfc2f10b1e8d524a9df7f08a0716eccc3bedf6e235da"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Battle-55b5860b.json"
tag = "bytebeasts-Battle"
manifest_name = "bytebeasts-Battle-55b5860b"

[[models.members]]
name = "battle_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "u32"
key = false

[[models.members]]
name = "opponent_id"
type = "u32"
key = false

[[models.members]]
name = "active_beast_player"
type = "u32"
key = false

[[models.members]]
name = "active_beast_opponent"
type = "u32"
key = false

[[models.members]]
name = "battle_active"
type = "u32"
key = false

[[models.members]]
name = "turn"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7fe3d50195b0f91ee8bcbc17710f62df6f2d31732540b74b8b7dd7fc2157d9f"
original_class_hash = "0x7fe3d50195b0f91ee8bcbc17710f62df6f2d31732540b74b8b7dd7fc2157d9f"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Beast-27809d20.json"
tag = "bytebeasts-Beast"
manifest_name = "bytebeasts-Beast-27809d20"

[[models.members]]
name = "beast_id"
type = "u32"
key = true

[[models.members]]
name = "beast_name"
type = "felt252"
key = false

[[models.members]]
name = "beast_type"
type = "u32"
key = false

[[models.members]]
name = "beast_description"
type = "felt252"
key = false

[[models.members]]
name = "player_id"
type = "u32"
key = false

[[models.members]]
name = "hp"
type = "u32"
key = false

[[models.members]]
name = "current_hp"
type = "u32"
key = false

[[models.members]]
name = "attack"
type = "u32"
key = false

[[models.members]]
name = "defense"
type = "u32"
key = false

[[models.members]]
name = "mt1"
type = "u32"
key = false

[[models.members]]
name = "mt2"
type = "u32"
key = false

[[models.members]]
name = "mt3"
type = "u32"
key = false

[[models.members]]
name = "mt4"
type = "u32"
key = false

[[models.members]]
name = "level"
type = "u32"
key = false

[[models.members]]
name = "experience_to_next_level"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4382e91986019f8da68643f9db2564598ab2c919fce4e62c2d860d86a868923"
original_class_hash = "0x4382e91986019f8da68643f9db2564598ab2c919fce4e62c2d860d86a868923"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Mt-37360d30.json"
tag = "bytebeasts-Mt"
manifest_name = "bytebeasts-Mt-37360d30"

[[models.members]]
name = "mt_id"
type = "u32"
key = true

[[models.members]]
name = "mt_name"
type = "felt252"
key = false

[[models.members]]
name = "mt_type"
type = "u32"
key = false

[[models.members]]
name = "mt_power"
type = "u32"
key = false

[[models.members]]
name = "mt_accuracy"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6bfeffff027de9cb3d94085db3c9963e42a8173ae8211a83ae71b9e57bc800e"
original_class_hash = "0x6bfeffff027de9cb3d94085db3c9963e42a8173ae8211a83ae71b9e57bc800e"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Player-14f5e45e.json"
tag = "bytebeasts-Player"
manifest_name = "bytebeasts-Player-14f5e45e"

[[models.members]]
name = "player_id"
type = "u32"
key = true

[[models.members]]
name = "player_name"
type = "felt252"
key = false

[[models.members]]
name = "beast_1"
type = "u32"
key = false

[[models.members]]
name = "beast_2"
type = "u32"
key = false

[[models.members]]
name = "beast_3"
type = "u32"
key = false

[[models.members]]
name = "beast_4"
type = "u32"
key = false

[[models.members]]
name = "potions"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x164879a36700032b1af24f1b5bcc6f8cd74c90fc259090049877a09b0dac57d"
original_class_hash = "0x164879a36700032b1af24f1b5bcc6f8cd74c90fc259090049877a09b0dac57d"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Potion-6a2114b0.json"
tag = "bytebeasts-Potion"
manifest_name = "bytebeasts-Potion-6a2114b0"

[[models.members]]
name = "potion_id"
type = "u32"
key = true

[[models.members]]
name = "potion_name"
type = "felt252"
key = false

[[models.members]]
name = "potion_effect"
type = "u32"
key = false
