[world]
kind = "WorldContract"
class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
original_class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x644001b28f89e7ae8a39f9c48eb4961cc4f817dc40b4b527f851a56fe703652"
transaction_hash = "0x1f1c658f1b3de98e21e98839833fb636773cf806eb7d2e3d3ec52e35c35a78"
block_number = 3
seed = "bytebeasts"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://0.0.0.0:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x4854bb6cc04b51e5adaed76afc0664091182fe44a9e5e68dc4f8f5f59ffd464"
class_hash = "0x67da38ec020e7951f00fe7d3adf8315bb0d4ee1c3b7eb509e464bce3f1f1173"
original_class_hash = "0x67da38ec020e7951f00fe7d3adf8315bb0d4ee1c3b7eb509e464bce3f1f1173"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/bytebeasts-actions-648ac931.json"
reads = []
writes = [
    "bytebeasts-Moves",
    "bytebeasts-Position",
    "bytebeasts-DirectionsAvailable",
]
init_calldata = []
tag = "bytebeasts-actions"
manifest_name = "bytebeasts-actions-648ac931"

[[models]]
kind = "DojoModel"
class_hash = "0x2edfc0419e5dc0630fe45e0d983b8273119c14ac89e544926c34f48c6f5605e"
original_class_hash = "0x2edfc0419e5dc0630fe45e0d983b8273119c14ac89e544926c34f48c6f5605e"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Beast-27809d20.json"
tag = "bytebeasts-Beast"
manifest_name = "bytebeasts-Beast-27809d20"

[[models.members]]
name = "beast_id"
type = "u32"
key = true

[[models.members]]
name = "beast_name"
type = "u32"
key = false

[[models.members]]
name = "beast_type"
type = "u32"
key = false

[[models.members]]
name = "beast_description"
type = "u32"
key = false

[[models.members]]
name = "player_id"
type = "u32"
key = false

[[models.members]]
name = "hp"
type = "u32"
key = false

[[models.members]]
name = "current_hp"
type = "u32"
key = false

[[models.members]]
name = "attack"
type = "u64"
key = false

[[models.members]]
name = "defense"
type = "u64"
key = false

[[models.members]]
name = "mt1"
type = "u32"
key = false

[[models.members]]
name = "mt2"
type = "u32"
key = false

[[models.members]]
name = "mt3"
type = "u32"
key = false

[[models.members]]
name = "mt4"
type = "u32"
key = false

[[models.members]]
name = "level"
type = "u32"
key = false

[[models.members]]
name = "experience_to_nex_level"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x74fa5d0e4e909cd9ad439cc2efe9fb6bb33d848f4e7a4156674f44a0218ab13"
original_class_hash = "0x74fa5d0e4e909cd9ad439cc2efe9fb6bb33d848f4e7a4156674f44a0218ab13"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Message-23adac1f.json"
tag = "bytebeasts-Message"
manifest_name = "bytebeasts-Message-23adac1f"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "message"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4382e91986019f8da68643f9db2564598ab2c919fce4e62c2d860d86a868923"
original_class_hash = "0x4382e91986019f8da68643f9db2564598ab2c919fce4e62c2d860d86a868923"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Mt-37360d30.json"
tag = "bytebeasts-Mt"
manifest_name = "bytebeasts-Mt-37360d30"

[[models.members]]
name = "mt_id"
type = "u32"
key = true

[[models.members]]
name = "mt_name"
type = "felt252"
key = false

[[models.members]]
name = "mt_type"
type = "u32"
key = false

[[models.members]]
name = "mt_power"
type = "u32"
key = false

[[models.members]]
name = "mt_accuracy"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6bfeffff027de9cb3d94085db3c9963e42a8173ae8211a83ae71b9e57bc800e"
original_class_hash = "0x6bfeffff027de9cb3d94085db3c9963e42a8173ae8211a83ae71b9e57bc800e"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Player-14f5e45e.json"
tag = "bytebeasts-Player"
manifest_name = "bytebeasts-Player-14f5e45e"

[[models.members]]
name = "player_id"
type = "u32"
key = true

[[models.members]]
name = "player_name"
type = "felt252"
key = false

[[models.members]]
name = "beast_1"
type = "u32"
key = false

[[models.members]]
name = "beast_2"
type = "u32"
key = false

[[models.members]]
name = "beast_3"
type = "u32"
key = false

[[models.members]]
name = "beast_4"
type = "u32"
key = false

[[models.members]]
name = "potions"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x164879a36700032b1af24f1b5bcc6f8cd74c90fc259090049877a09b0dac57d"
original_class_hash = "0x164879a36700032b1af24f1b5bcc6f8cd74c90fc259090049877a09b0dac57d"
abi = "manifests/dev/deployment/abis/models/bytebeasts-Potion-6a2114b0.json"
tag = "bytebeasts-Potion"
manifest_name = "bytebeasts-Potion-6a2114b0"

[[models.members]]
name = "potion_id"
type = "u32"
key = true

[[models.members]]
name = "potion_name"
type = "felt252"
key = false

[[models.members]]
name = "potion_effect"
type = "u32"
key = false
