kind = "DojoModel"
class_hash = "0x3eda97055345dbd80570f5264558b4f6e91ac0eeea273996cf8b986d984db2c"
original_class_hash = "0x3eda97055345dbd80570f5264558b4f6e91ac0eeea273996cf8b986d984db2c"
abi = "manifests/dev/base/abis/models/bytebeasts-Moves-b282ed29.json"
tag = "bytebeasts-Moves"
manifest_name = "bytebeasts-Moves-b282ed29"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false

[[members]]
name = "can_move"
type = "bool"
key = false
