kind = "DojoModel"
class_hash = "0x7bef5c17e52dab476cd7ae664bbb0f0024aae955ed8b12592e2d6faf7ff6a3c"
original_class_hash = "0x7bef5c17e52dab476cd7ae664bbb0f0024aae955ed8b12592e2d6faf7ff6a3c"
abi = "manifests/dev/base/abis/models/bytebeasts-Beast-27809d20.json"
tag = "bytebeasts-Beast"
manifest_name = "bytebeasts-Beast-27809d20"

[[members]]
name = "beast_id"
type = "u32"
key = true

[[members]]
name = "beast_name"
type = "felt252"
key = false

[[members]]
name = "beast_type"
type = "WorldElements"
key = false

[[members]]
name = "beast_description"
type = "felt252"
key = false

[[members]]
name = "player_id"
type = "u32"
key = false

[[members]]
name = "hp"
type = "u32"
key = false

[[members]]
name = "current_hp"
type = "u32"
key = false

[[members]]
name = "attack"
type = "u32"
key = false

[[members]]
name = "defense"
type = "u32"
key = false

[[members]]
name = "mt1"
type = "u32"
key = false

[[members]]
name = "mt2"
type = "u32"
key = false

[[members]]
name = "mt3"
type = "u32"
key = false

[[members]]
name = "mt4"
type = "u32"
key = false

[[members]]
name = "level"
type = "u32"
key = false

[[members]]
name = "experience_to_next_level"
type = "u64"
key = false
