kind = "DojoModel"
class_hash = "0x753774dc80b9e6dbdd5939e356065e11745d14e14217fb69e4c35a7b93defd2"
original_class_hash = "0x753774dc80b9e6dbdd5939e356065e11745d14e14217fb69e4c35a7b93defd2"
abi = "manifests/dev/base/abis/models/bytebeasts-DirectionsAvailable-48430624.json"
tag = "bytebeasts-DirectionsAvailable"
manifest_name = "bytebeasts-DirectionsAvailable-48430624"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "directions"
type = "Array<Direction>"
key = false
