kind = "DojoModel"
class_hash = "0x5ba495f80b653be6df964eb97ac2e7b3f7f72508d17b54b1d51595231db8fae"
original_class_hash = "0x5ba495f80b653be6df964eb97ac2e7b3f7f72508d17b54b1d51595231db8fae"
abi = "manifests/dev/base/abis/models/bytebeasts-StatusBattle-161fdb64.json"
tag = "bytebeasts-StatusBattle"
manifest_name = "bytebeasts-StatusBattle-161fdb64"

[[members]]
name = "battle_id"
type = "u32"
key = true

[[members]]
name = "message"
type = "felt252"
key = false
