kind = "DojoModel"
class_hash = "0x4832e8416049ae631fdf6d424b02a9fbf366810cfd1dd4d9d047b58809e138a"
original_class_hash = "0x4832e8416049ae631fdf6d424b02a9fbf366810cfd1dd4d9d047b58809e138a"
abi = "manifests/dev/base/abis/models/bytebeasts-Moved-2a5b60a4.json"
tag = "bytebeasts-Moved"
manifest_name = "bytebeasts-Moved-2a5b60a4"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "direction"
type = "Direction"
key = false
