kind = "DojoModel"
class_hash = "0x6bfeffff027de9cb3d94085db3c9963e42a8173ae8211a83ae71b9e57bc800e"
original_class_hash = "0x6bfeffff027de9cb3d94085db3c9963e42a8173ae8211a83ae71b9e57bc800e"
abi = "manifests/dev/base/abis/models/bytebeasts-Player-14f5e45e.json"
tag = "bytebeasts-Player"
manifest_name = "bytebeasts-Player-14f5e45e"

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "player_name"
type = "felt252"
key = false

[[members]]
name = "beast_1"
type = "u32"
key = false

[[members]]
name = "beast_2"
type = "u32"
key = false

[[members]]
name = "beast_3"
type = "u32"
key = false

[[members]]
name = "beast_4"
type = "u32"
key = false

[[members]]
name = "potions"
type = "u32"
key = false
