kind = "DojoModel"
class_hash = "0x239c54e950b5c50d445f9a8db758ea0af1440b75a5f1921dfe014b927476c32"
original_class_hash = "0x239c54e950b5c50d445f9a8db758ea0af1440b75a5f1921dfe014b927476c32"
abi = "manifests/dev/base/abis/models/bytebeasts-Battle-55b5860b.json"
tag = "bytebeasts-Battle"
manifest_name = "bytebeasts-Battle-55b5860b"

[[members]]
name = "battle_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = false

[[members]]
name = "opponent_id"
type = "u32"
key = false

[[members]]
name = "active_beast_player"
type = "u32"
key = false

[[members]]
name = "active_beast_opponent"
type = "u32"
key = false

[[members]]
name = "battle_active"
type = "u32"
key = false

[[members]]
name = "turn"
type = "u32"
key = false
