kind = "DojoModel"
class_hash = "0xe446a8c3773fbfae6e2e0e87a6d1db12143224cf47e217e12bf9cfc76428ef"
original_class_hash = "0xe446a8c3773fbfae6e2e0e87a6d1db12143224cf47e217e12bf9cfc76428ef"
abi = "manifests/dev/base/abis/models/bytebeasts-Status-6595af0f.json"
tag = "bytebeasts-Status"
manifest_name = "bytebeasts-Status-6595af0f"

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "message"
type = "felt252"
key = false
