kind = "DojoModel"
class_hash = "0x5d992305e6f7ce0965d5bbe71e33cab817c31514ba83c8fca4610ab574e8016"
original_class_hash = "0x5d992305e6f7ce0965d5bbe71e33cab817c31514ba83c8fca4610ab574e8016"
abi = "manifests/dev/base/abis/models/bytebeasts-Player-14f5e45e.json"
tag = "bytebeasts-Player"
manifest_name = "bytebeasts-Player-14f5e45e"

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "player_name"
type = "felt252"
key = false

[[members]]
name = "beast_1"
type = "u32"
key = false

[[members]]
name = "beast_2"
type = "u32"
key = false

[[members]]
name = "beast_3"
type = "u32"
key = false

[[members]]
name = "beast_4"
type = "u32"
key = false

[[members]]
name = "potions"
type = "u32"
key = false
