kind = "DojoModel"
class_hash = "0x74fa5d0e4e909cd9ad439cc2efe9fb6bb33d848f4e7a4156674f44a0218ab13"
original_class_hash = "0x74fa5d0e4e909cd9ad439cc2efe9fb6bb33d848f4e7a4156674f44a0218ab13"
abi = "manifests/dev/base/abis/models/bytebeasts-Message-23adac1f.json"
tag = "bytebeasts-Message"
manifest_name = "bytebeasts-Message-23adac1f"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "message"
type = "felt252"
key = false
