kind = "DojoModel"
class_hash = "0x6af5b71c9083b4f04473fb37b47ec2f2ff51641314c20dd2bd186c90d5e8395"
original_class_hash = "0x6af5b71c9083b4f04473fb37b47ec2f2ff51641314c20dd2bd186c90d5e8395"
abi = "manifests/dev/base/abis/models/bytebeasts-Position-78f28df6.json"
tag = "bytebeasts-Position"
manifest_name = "bytebeasts-Position-78f28df6"

[[members]]
name = "player"
type = "Player"
key = true

[[members]]
name = "coordinates"
type = "Coordinates"
key = false
