kind = "DojoModel"
class_hash = "0x91da9f380b960e2dc7f9a59d4e1242ed718590d2270fd28e2311a5e1ee54f2"
original_class_hash = "0x91da9f380b960e2dc7f9a59d4e1242ed718590d2270fd28e2311a5e1ee54f2"
abi = "manifests/dev/base/abis/models/bytebeasts-Position-78f28df6.json"
tag = "bytebeasts-Position"
manifest_name = "bytebeasts-Position-78f28df6"

[[members]]
name = "player"
type = "Player"
key = true

[[members]]
name = "coordinates"
type = "Coordinates"
key = false
