kind = "DojoModel"
class_hash = "0x14996dadc46ccc2e22fa71e614ea4a158f91fd919429d00a0e36a4a4314bdd8"
original_class_hash = "0x14996dadc46ccc2e22fa71e614ea4a158f91fd919429d00a0e36a4a4314bdd8"
abi = "manifests/dev/base/abis/models/bytebeasts-Game-e91217d7.json"
tag = "bytebeasts-Game"
manifest_name = "bytebeasts-Game-e91217d7"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "player_1"
type = "ContractAddress"
key = false

[[members]]
name = "player_2"
type = "ContractAddress"
key = false

[[members]]
name = "player_3"
type = "ContractAddress"
key = false

[[members]]
name = "player_4"
type = "ContractAddress"
key = false

[[members]]
name = "status"
type = "GameStatus"
key = false

[[members]]
name = "is_private"
type = "bool"
key = false
