kind = "DojoModel"
class_hash = "0x7dc1689aa3f1e6b123cadfed4066a70f09be69c9a166bfe824c61b916925efe"
original_class_hash = "0x7dc1689aa3f1e6b123cadfed4066a70f09be69c9a166bfe824c61b916925efe"
abi = "manifests/dev/base/abis/models/bytebeasts-GameId-344511d3.json"
tag = "bytebeasts-GameId"
manifest_name = "bytebeasts-GameId-344511d3"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "game_id"
type = "u128"
key = false
