kind = "DojoModel"
class_hash = "0x144b4dd55fa65d6e78e37571cee889759040f43772e7ee2d2eaa7b3c36b880c"
original_class_hash = "0x144b4dd55fa65d6e78e37571cee889759040f43772e7ee2d2eaa7b3c36b880c"
abi = "manifests/dev/base/abis/models/bytebeasts-Position-78f28df6.json"
tag = "bytebeasts-Position"
manifest_name = "bytebeasts-Position-78f28df6"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "vec"
type = "Vec2"
key = false
